services:
  web0:
    image: web0
    build:
      dockerfile: ./80.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
  web1:
    image: web1
    build:
      dockerfile: ./81.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: forum
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
