services:
  vulnerable-dubbo:
    build: .
    container_name: dubbo-cve-2019-17564
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    networks:
      - dubbo-test

  # Optional: Add a simple web interface to test the vulnerability
  test-client:
    image: curlimages/curl:latest
    container_name: dubbo-test-client
    depends_on:
      - vulnerable-dubbo
    networks:
      - dubbo-test
    command: >
      sh -c "
        echo 'Waiting for Dubbo to start...' &&
        sleep 10 &&
        echo 'Testing basic connectivity...' &&
        curl -f http://vulnerable-dubbo:8080/ || echo 'Dubbo not ready yet' &&
        echo 'Testing CVE-2019-17564 vulnerability...' &&
        curl -X POST http://vulnerable-dubbo:8080/ \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'interface=com.example.TestService&method=test&parameterTypes=java.lang.String&parameter=AAAAAA' &&
        echo 'Vulnerability test completed. Check logs for details.'
      "

networks:
  dubbo-test:
    driver: bridge 