version: '3.8'
services:
  nginx-vulnerable:
    image: nginx:latest
    container_name: http-missing-security-headers-lab
    ports:
      - "8080:80"
    restart: always
    stdin_open: true
    command: >
      sh -c "echo 'worker_processes 1;

      events {
          worker_connections 1024;
      }

      http {
          include mime.types;
          default_type application/octet-stream;

          server {
              listen 80;
              server_name localhost;

              location / {
                  root /usr/share/nginx/html;
                  index index.html;
              }

              # No security headers - Vulnerable setup
              add_header X-Debug \"Vulnerable Server\" always;
          }
      }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
