version: '3.8'
services:
  nginx-vulnerable:
    image: nginx:latest  # Pulls the official Nginx image
    container_name: nginx-vulnerable
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
